### ISSUE TITLE
Creating new user as admin throws error

### ISSUE THREAD

**Issue by Nnanyielugo** [EasyERP/EasyERP_open_source#13]
Creating a new user in system users throws a 404 error with a 'something is wrong' message.

It also prints his error stack in terminal.

`POST /users/ 404 12.670 ms - 12
2017-10-16T15:55:27.453Z - error:
Error
    at Object.User.create [as handle] (/home/nnanyielugo/Workspace/CRM/handlers/user.js:740:19)
    at next_layer (/home/nnanyielugo/Workspace/CRM/node_modules/express/lib/router/route.js:103:13)
    at sender (/home/nnanyielugo/Workspace/CRM/helpers/access.js:136:13)
    at EventEmitter.<anonymous> (/home/nnanyielugo/Workspace/CRM/helpers/access.js:67:13)
    at EventEmitter.<anonymous> (/home/nnanyielugo/Workspace/CRM/node_modules/mpromise/lib/promise.js:175:45)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at Promise.safeEmit (/home/nnanyielugo/Workspace/CRM/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.fulfill (/home/nnanyielugo/Workspace/CRM/node_modules/mpromise/lib/promise.js:94:24)
    at Promise.resolve (/home/nnanyielugo/Workspace/CRM/node_modules/mongoose/lib/promise.js:113:23)
    at handleCallback (/home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1595:7
    at handleCallback (/home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb/lib/db.js:253:5
    at /home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:795:13
    at Callbacks.emit (/home/nnanyielugo/Workspace/CRM/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:94:3)`

**Comment by jacksolutions** [comment]
i am also getting the same error

Error
    at Object.User.create [as handle] (/Users/jacksolutions/Documents/easyerp/handlers/user.js:740:19)
    at next_layer (/Users/jacksolutions/Documents/easyerp/node_modules/express/lib/router/route.js:103:13)
    at sender (/Users/jacksolutions/Documents/easyerp/helpers/access.js:136:13)
    at /Users/jacksolutions/Documents/easyerp/helpers/access.js:67:13
    at /Users/jacksolutions/Documents/easyerp/node_modules/mongoose/lib/model.js:4054:16
    at /Users/jacksolutions/Documents/easyerp/node_modules/mongoose/lib/aggregate.js:767:13
    at /Users/jacksolutions/Documents/easyerp/node_modules/mongoose/node_modules/kareem/index.js:131:16
    at process._tickCallback (internal/process/next_tick.js:150:11)
