### ISSUE TITLE
Getting Error : http://localhost:8089/users/current 404 (Not Found)

### ISSUE THREAD

**Issue by nabaragpaul** [EasyERP/EasyERP_open_source#3]
After install all the dependency and dumping the databases with mongorestore , when i start the server and open localhost:8089 , its showing Error http://localhost:8089/users/current 404 (Not Found). i am also getting error in console ... following is the error log 

at Object.module.exports [as handle] (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/helpers/checkAuth.js:9:11)
    at next_layer (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/route.js:107:5)
    at /var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:213:24
    at Function.proto.process_params (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:284:12)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:207:19)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:182:38)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:182:38)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:182:38)
    at Function.proto.handle (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:154:3)
    at Layer.router (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:24:12)
    at trim_prefix (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:255:15)
    at /var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:216:9
    at Function.proto.process_params (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:284:12)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:207:19)
    at next (/var/www/R&D/easyERP_from_git_clone_working/EasyERP_open_source/node_modules/express/lib/router/index.js:182:38)
GET /users/current 404 6.971 ms - 12
GET /account/authenticated?_=1486699693901 401 3.216 ms - 12

Can anyone please help me out what i am missing here .All help will be appreciated.

**Comment by PikinerLiliya** [comment]
Give us screen of home page and list of mongodb databases, we will try to help you. Thank you for your issue
