### ISSUE TITLE
Get an empty App after starting!

### ISSUE THREAD

**Issue by xuantubo** [EasyERP/EasyERP_open_source#4]
Hello folks,

I'm getting below error after starting. It looks like an empty  App.
Really appreciate to get your advice.

Cheers.

GET /users/current 500 3.612 ms - 66
2017-02-22T09:45:19.388Z - error: exception: Unrecognized pipeline stage name: '$lookup'
MongoError: exception: Unrecognized pipeline stage name: '$lookup'
    at Function.MongoError.create (/TuBo/private_projects/bufffalo-kids/taman/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /TuBo/private_projects/bufffalo-kids/taman/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:793:66
    at Callbacks.emit (/TuBo/private_projects/bufffalo-kids/taman/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at Connection.messageHandler (/TuBo/private_projects/bufffalo-kids/taman/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/TuBo/private_projects/bufffalo-kids/taman/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by PikinerLiliya** [comment]
Hello, the reason is in version of mongodb. You need to install mongodb starting from 3.0

**Comment by xuantubo** [comment]
Thank @PikinerLiliya ,

After upgrading the version of MongoDB to latest. It works perfectly!

Cheers.
